@url = http://localhost:52771/api

@userId = 115

@token = 0

###
GET {{url}}/users

###
GET {{url}}/users/{{userId}}

###
POST {{url}}/users
Content-Type: application/json

{
  "firstName": "FirstName8",
  "lastName": "LastName8",
  "login": "Login8",
  "email": "emai1l@wp.pl",
  "isActive": true,
  "lastLogin": null,
  "usersAuthTokens": null,
  "passwords": null,
  "usersGroups": null
}

###
DELETE {{url}}/users/{{userId}}

###
GET {{url}}/account/me

###
POST {{url}}/account/login
Content-Type: application/json

{
  "email": "email@wp.pl1",
  "password": "test"
}
