@url = http://localhost:5000/api

@userId = 0

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyQHdwLnBsIiwianRpIjoiMjhmNmIyMWUtMDdkZi00ZGVjLTlkYmUtNzQ5YjJlOTFmZDQwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsIm5iZiI6MTUyOTYxMjA0NSwiZXhwIjoxNTI5NjEyMTA1LCJpc3MiOiJhdXRoZW50aWNhdGlvblNlcnZlciJ9.BYSS8oHR3_mo8yBthUdgpc80t3fzfG41-j9Zj66N32Q

###
GET {{url}}/users

###
GET {{url}}/users/{{userId}}

###
POST {{url}}/users
Content-Type: application/json

{
  "firstName": "admin",
  "lastName": "LastName8",
  "login": "Login8",
  "email": "admin@wp.pl",
  "isActive": true,
  "lastLogin": null,
  "password":"admin1",
  "role":"admin",
  "usersAuthTokens": null,
  "passwords": null,
  "usersGroups": null
}

###
DELETE {{url}}/users/{{userId}}

###
GET {{url}}/account/me
Authorization: Bearer {{token}}

###
POST {{url}}/account/login
Content-Type: application/json

{
  "email": "admin@wp.pl",
  "password": "admin1",
  "role":"admin"
}

###
POST {{url}}/account/login
Content-Type: application/json

{
  "email": "user@wp.pl",
  "password": "user1",
  "role":"user"
}

###
POST {{url}}/account/register
Content-Type: application/json

{
  "email": "emai2l@wp.pl",
  "password": "test"
}

###
GET {{url}}/account/protected
Authorization: Bearer {{token}}


###
GET {{url}}/account/protectedadmin
Authorization: Bearer {{token}}

###
GET {{url}}/account/protecteduser
Authorization: Bearer {{token}}





