@url = http://localhost:5000/api

@userId = 12

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyQHdwLnBsIiwianRpIjoiMmU5MmI2Y2EtMmQ5Yi00NDkzLTkwNTMtYTVhZDkyMTFiZGViIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsIm5iZiI6MTUyOTY0ODIxNSwiZXhwIjoxNTI5NjQ4Mjc1LCJpc3MiOiJhdXRoZW50aWNhdGlvblNlcnZlciJ9.EXQN_pNdCVu9crcxYVDmhG8J-NiFMMhOOgmFSHv_aoM

###
GET {{url}}/users

###
GET {{url}}/users/{{userId}}

###
POST {{url}}/users
Content-Type: application/json

{
  "firstName": "userwithoutright1",
  "lastName": "LastName81",
  "login": "Login8",
  "email": "userwithoutright1@wp.pl",
  "isActive": true,
  "lastLogin": null,
  "password":"userwithoutright1",
  "role":"userwithoutright1",
  "usersAuthTokens": null,
  "passwords": null,
  "usersGroups": null
}

###
DELETE {{url}}/users/{{userId}}


###
POST {{url}}/account/login
Content-Type: application/json

{
  "email": "admin@wp.pl",
  "password": "admin1",
  "role":"admin"
}

###
POST {{url}}/account/login
Content-Type: application/json

{
  "email": "user@wp.pl",
  "password": "user1",
  "role":"user"
}

###
POST {{url}}/account/login
Content-Type: application/json

{
  "email": "userwithoutright@wp.pl",
  "password": "userwithoutright",
  "role":"userwithoutright"
}

###
POST {{url}}/account/register
Content-Type: application/json

{
  "email": "emai2l@wp.pl",
  "password": "test"
}

###
GET {{url}}/account/me
Authorization: Bearer {{token}}

###
GET {{url}}/account/protectedadmin
Authorization: Bearer {{token}}

###
GET {{url}}/account/protecteduser
Authorization: Bearer {{token}}





