// <auto-generated />
using System;
using AuthenticationServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthenticationServer.Data.Migrations
{
    [DbContext(typeof(AuthenticationServerDbContext))]
    [Migration("20180611133914_UserAuthTokens")]
    partial class UserAuthTokens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuthenticationServer.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("LastLogin");

                    b.Property<string>("LastName");

                    b.Property<string>("Login");

                    b.Property<int>("UserAuthTokens");

                    b.Property<int>("UsersAuthTokensId");

                    b.HasKey("Id");

                    b.HasIndex("UserAuthTokens");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AuthenticationServer.Domain.UserAuthTokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("UsersAuthTokens");
                });

            modelBuilder.Entity("AuthenticationServer.Domain.User", b =>
                {
                    b.HasOne("AuthenticationServer.Domain.UserAuthTokens", "UsersAuthTokens")
                        .WithMany("Users")
                        .HasForeignKey("UserAuthTokens")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
